# Generated by Django 5.2 on 2026-01-20 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomia', '0006_alter_aeronavegeral_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaAeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_obs', models.CharField(blank=True, max_length=100, null=True)),
                ('destino_obs', models.CharField(blank=True, max_length=100, null=True)),
                ('alternativa_voo', models.CharField(blank=True, max_length=100, null=True)),
                ('alternativa_obs', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria_spf', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('operador', models.CharField(blank=True, max_length=100, null=True)),
                ('operador_detalhe', models.CharField(blank=True, max_length=100, null=True)),
                ('operacao', models.CharField(blank=True, max_length=100, null=True)),
                ('fase_voo', models.CharField(blank=True, max_length=100, null=True)),
                ('danos', models.CharField(blank=True, max_length=100, null=True)),
                ('custo_reparo', models.CharField(blank=True, max_length=100, null=True)),
                ('fabricante_cenipa', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomia.aeronavegeral', verbose_name='Matrícula')),
                ('destino_voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino_voo', to='taxonomia.aerodromogeral', verbose_name='Destino do Voo')),
                ('origem_voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem_voo', to='taxonomia.aerodromogeral', verbose_name='Origem do Voo')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Artefato',
                'db_table': 'ocorrencia_aeronave',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaAeronaveLesao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_lesao', models.CharField(blank=True, choices=[('FATAL', 'Fatal'), ('GRAVE', 'Grave'), ('LEVE', 'Leve'), ('ILESO', 'Ileso'), ('INDETERMINADO', 'Indeterminado')], max_length=50, null=True, verbose_name='Tipo de Lesão')),
                ('categoria', models.CharField(blank=True, choices=[('TRIPULANTE', 'Tripulante'), ('PASSAGEIRO', 'Passageiro'), ('TERCEIROS', 'Terceiros')], max_length=50, null=True, verbose_name='Categoria')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ocorrencia_aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_aeronave_lesao', to='ocorrencia.ocorrenciaaeronave', verbose_name='Ocorrência Aeronave')),
            ],
            options={
                'verbose_name': 'Lesão',
                'verbose_name_plural': 'Ocorrência Aeronave Lesão',
                'db_table': 'ocorrencia_aeronave_lesao',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaAeronaveTripulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('funcao', models.CharField(blank=True, choices=[('PILOTO', 'Piloto'), ('COPILOTO', 'Copiloto'), ('MECÂNICO DE VOO', 'Mecânico de Voo'), ('COMISSÁRIO', 'Comissário'), ('INSTRUTOR', 'Instrutor'), ('ALUNO', 'Aluno'), ('OUTRO', 'Outro')], max_length=50, null=True, verbose_name='Função a Bordo')),
                ('licenca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Licença')),
                ('habilitacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Habilitação')),
                ('validade_cma', models.DateField(blank=True, null=True, verbose_name='Validade CMA')),
                ('validade_habilitacao', models.DateField(blank=True, null=True, verbose_name='Validade Habilitação')),
                ('horas_totais', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horas Totais de Voo')),
                ('horas_equipamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horas no Equipamento')),
                ('horas_ultimos_30_dias', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horas Últimos 30 Dias')),
                ('horas_ultimas_24_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horas Últimas 24 Horas')),
                ('idade', models.IntegerField(blank=True, null=True, verbose_name='Idade')),
                ('formacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Formação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ocorrencia_aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_aeronave_tripulante', to='ocorrencia.ocorrenciaaeronave', verbose_name='Ocorrência Aeronave')),
            ],
            options={
                'verbose_name': 'Tripulante',
                'verbose_name_plural': 'Ocorrência Aeronave Tripulante',
                'db_table': 'ocorrencia_aeronave_tripulante',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, null=True)),
                ('numero_processo', models.CharField(max_length=100, null=True)),
                ('publico', models.BooleanField(null=True)),
                ('rbac103', models.BooleanField(null=True)),
                ('classificacao', models.CharField(choices=[('ACIDENTE', 'ACIDENTE'), ('INCIDENTE', 'INCIDENTE'), ('INCIDENTE GRAVE', 'INCIDENTE GRAVE'), ('OCORRÊNCIA SOLO', 'OCORRÊNCIA SOLO'), ('OCORRÊNCIA ANORMAL', 'OCORRÊNCIA ANORMAL')], max_length=50, null=True, verbose_name='Classificação')),
                ('dia_comunicacao', models.DateField(null=True, verbose_name='Dia comunicação')),
                ('dia', models.DateField(null=True, verbose_name='Dia')),
                ('horario', models.TimeField(null=True, verbose_name='Hora')),
                ('dia_utc', models.DateField(null=True, verbose_name='Dia UTC')),
                ('horario_utc', models.TimeField(null=True, verbose_name='Hora UTC')),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude_decimal', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude_decimal', models.CharField(blank=True, max_length=100, null=True)),
                ('danos_terceiros', models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO'), ('INDETERMINADO', 'INDETERMINADO')], max_length=100, null=True)),
                ('historico', models.TextField(null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('key_eccairs', models.CharField(blank=True, max_length=100, null=True)),
                ('file_number_eccairs', models.CharField(blank=True, max_length=100, null=True)),
                ('cadastrado_em', models.DateField(auto_now_add=True)),
                ('aerodromo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxonomia.aerodromogeral', verbose_name='Aeródromo')),
                ('cadastrado_por_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxonomia.geografiacidade')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Geral',
                'db_table': 'ocorrencia_geral',
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaFatorHumano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_fator_humano', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Fator Humano',
                'db_table': 'ocorrencia_fator_humano',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaFatorContribuinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_fator_contribuinte', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Fator Contribuinte',
                'db_table': 'ocorrencia_fator_contribuinte',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_documento', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Documento',
                'db_table': 'ocorrencia_documento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_controle', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Controle',
                'db_table': 'ocorrencia_controle',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaConfirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_confirmacao', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Confirmação',
                'db_table': 'ocorrencia_confirmacao',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_comissao', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Comissão',
                'db_table': 'ocorrencia_comissao',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaAutenticacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_autenticacao', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Autenticação',
                'db_table': 'ocorrencia_autenticacao',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaAsoaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_asoaci', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência ASOACI',
                'db_table': 'ocorrencia_asoaci',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_apoio', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Apoio',
                'db_table': 'ocorrencia_apoio',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='ocorrencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_aeronave', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência'),
        ),
        migrations.CreateModel(
            name='OcorrenciaJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_juridico', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Jurídico',
                'db_table': 'ocorrencia_juridico',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaLabdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gravador', models.CharField(blank=True, choices=[('CVR', 'CVR - Cockpit Voice Recorder'), ('FDR', 'FDR - Flight Data Recorder'), ('COMBO', 'Combinado CVR/FDR'), ('OUTRO', 'Outro')], max_length=50, null=True, verbose_name='Tipo de Gravador')),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série')),
                ('status_recuperacao', models.CharField(blank=True, choices=[('RECUPERADO', 'Recuperado'), ('NAO_RECUPERADO', 'Não Recuperado'), ('PARCIALMENTE', 'Parcialmente Recuperado'), ('NAO_EQUIPADO', 'Aeronave Não Equipada'), ('INDETERMINADO', 'Indeterminado')], max_length=50, null=True, verbose_name='Status de Recuperação')),
                ('dados_extraidos', models.BooleanField(blank=True, null=True, verbose_name='Dados Extraídos')),
                ('data_extracao', models.DateField(blank=True, null=True, verbose_name='Data da Extração')),
                ('duracao_gravacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Duração da Gravação')),
                ('qualidade_dados', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualidade dos Dados')),
                ('laudo', models.TextField(blank=True, null=True, verbose_name='Laudo Técnico')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_labdata', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name': 'Gravador de Voo (LABDATA)',
                'verbose_name_plural': 'Ocorrência Aeronave LABDATA',
                'db_table': 'ocorrencia_aeronave_labdata',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaLaudoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_laudo_material', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Laudo Material',
                'db_table': 'ocorrencia_laudo_material',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaProgressoInvestigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_progresso_investigacao', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Progresso Investigação',
                'db_table': 'ocorrencia_progresso_investigacao',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaRecomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_recomendacao', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Recomendação',
                'db_table': 'ocorrencia_recomendacao',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaRegistroMinuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_registro_minuta', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Registro Minuta',
                'db_table': 'ocorrencia_registro_minuta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaRegistroRai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_registro_rai', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Registro RAI',
                'db_table': 'ocorrencia_registro_rai',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaRegistroRp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_registro_rp', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Registro RP',
                'db_table': 'ocorrencia_registro_rp',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_relatorio', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Relatório',
                'db_table': 'ocorrencia_relatorio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaRevisaoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_revisao_relatorio', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Revisão Relatório',
                'db_table': 'ocorrencia_revisao_relatorio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaRevisaoRelatorioFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_revisao_relatorio_feedback', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Revisão Relatório Feedback',
                'db_table': 'ocorrencia_revisao_relatorio_feedback',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaRevisaoRsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_revisao_rsv', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Revisão RSV',
                'db_table': 'ocorrencia_revisao_rsv',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaRevisaoSeripa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_revisao_seripa', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Revisão SERIPA',
                'db_table': 'ocorrencia_revisao_seripa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaTipoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_tipo_ocorrencia', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Tipo de Ocorrência',
                'db_table': 'ocorrencia_tipo_ocorrencia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaViolacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_violacao', to='ocorrencia.ocorrenciageral', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name_plural': 'Ocorrência Violação',
                'db_table': 'ocorrencia_violacao',
                'ordering': ['id'],
            },
        ),
    ]
