# Generated by Django 5.2 on 2026-01-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0002_fix_labdata_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocorrenciaaeronave',
            options={'ordering': ['id'], 'verbose_name_plural': 'ARTEFATO ESPECIAL'},
        ),
        migrations.AddField(
            model_name='ocorrenciageral',
            name='tipo',
            field=models.CharField(choices=[('Falha em lançamento', 'Falha em lançamento'), ('Anomalia em órbita', 'Anomalia em órbita'), ('Colisão / conjunção crítica', 'Colisão / conjunção crítica'), ('Reentrada controlada ou não controlada', 'Reentrada controlada ou não controlada'), ('Perda de comunicação', 'Perda de comunicação')], max_length=50, null=True, verbose_name='tipo'),
        ),
    ]
