# Generated by Django 5.2 on 2026-01-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0003_alter_ocorrenciaaeronave_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciacontrole',
            name='cadastrado_em',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ocorrenciacontrole',
            name='status',
            field=models.CharField(choices=[('INVESTIGADA', 'INVESTIGADA'), ('COLETA DE DADOS', 'COLETA DE DADOS')], max_length=100, null=True),
        ),
    ]
