# Generated by Django 5.2 on 2026-01-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0005_ocorrenciacontrole_investigador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciacontrole',
            name='orgao_investigador',
            field=models.CharField(choices=[('CENIPA', 'CENIPA'), ('OUTRO', 'OUTRO')], max_length=25, null=True),
        ),
    ]
