# Generated by Django 5.2 on 2026-01-21 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0006_ocorrenciacontrole_orgao_investigador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciacontrole',
            name='fez_acao_inicial',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO'), ('INDETERMINADO', 'INDETERMINADO')], max_length=25, null=True, verbose_name='Houve deslocamento até o local'),
        ),
        migrations.AlterField(
            model_name='ocorrenciacontrole',
            name='investigador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Investigador responsável'),
        ),
        migrations.AlterField(
            model_name='ocorrenciacontrole',
            name='orgao_investigador',
            field=models.CharField(choices=[('CENIPA', 'CENIPA'), ('OUTRO', 'OUTRO')], max_length=25, null=True, verbose_name='Orgão Investigador'),
        ),
        migrations.AlterField(
            model_name='ocorrenciacontrole',
            name='status',
            field=models.CharField(choices=[('INVESTIGADA', 'INVESTIGADA'), ('COLETA DE DADOS', 'COLETA DE DADOS')], max_length=100, null=True, verbose_name='Tratamento da Ocorrência'),
        ),
    ]
