# Generated by Django 5.2 on 2026-01-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0007_ocorrenciacontrole_fez_acao_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciageral',
            name='apogeu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Apogeu (km)'),
        ),
        migrations.AddField(
            model_name='ocorrenciageral',
            name='inclinacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Inclinação (graus)'),
        ),
        migrations.AddField(
            model_name='ocorrenciageral',
            name='latitude_impacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitude do Impacto'),
        ),
        migrations.AddField(
            model_name='ocorrenciageral',
            name='local_impacto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local de Impacto/Destroços'),
        ),
        migrations.AddField(
            model_name='ocorrenciageral',
            name='localizacao_tipo',
            field=models.CharField(blank=True, choices=[('EM_ORBITA', 'Em órbita'), ('EM_SOLO', 'Em solo (impacto ou destroços)')], max_length=20, null=True, verbose_name='Tipo de Localização'),
        ),
        migrations.AddField(
            model_name='ocorrenciageral',
            name='longitude_impacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitude do Impacto'),
        ),
        migrations.AddField(
            model_name='ocorrenciageral',
            name='orbita_tipo',
            field=models.CharField(blank=True, choices=[('LEO', 'LEO - Órbita Baixa da Terra'), ('MEO', 'MEO - Órbita Média da Terra'), ('GEO', 'GEO - Órbita Geoestacionária'), ('HEO', 'HEO - Órbita Altamente Elíptica'), ('INTERPLANETARIO', 'Interplanetário')], max_length=20, null=True, verbose_name='Tipo de Órbita'),
        ),
        migrations.AddField(
            model_name='ocorrenciageral',
            name='perigeu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Perigeu (km)'),
        ),
        migrations.AddField(
            model_name='ocorrenciageral',
            name='tle',
            field=models.TextField(blank=True, null=True, verbose_name='TLE (Two-Line Element)'),
        ),
    ]
