# Generated by Django 5.2 on 2026-01-21 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0008_ocorrenciageral_apogeu_ocorrenciageral_inclinacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrenciageral',
            name='rbac103',
        ),
    ]
