# Generated by Django 5.2 on 2026-01-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0009_remove_ocorrenciageral_rbac103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrenciageral',
            name='file_number_eccairs',
        ),
        migrations.RemoveField(
            model_name='ocorrenciageral',
            name='key_eccairs',
        ),
        migrations.AlterField(
            model_name='ocorrenciageral',
            name='classificacao',
            field=models.CharField(choices=[('ACIDENTE', 'ACIDENTE'), ('INCIDENTE', 'INCIDENTE'), ('INCIDENTE GRAVE', 'INCIDENTE GRAVE')], max_length=50, null=True, verbose_name='Classificação'),
        ),
    ]
