# Generated by Django 5.2 on 2026-01-21 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0010_remove_ocorrenciageral_file_number_eccairs_and_more'),
        ('taxonomia', '0006_alter_aeronavegeral_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrenciaaeronave',
            name='alternativa_obs',
        ),
        migrations.RemoveField(
            model_name='ocorrenciaaeronave',
            name='alternativa_voo',
        ),
        migrations.RemoveField(
            model_name='ocorrenciaaeronave',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='ocorrenciaaeronave',
            name='categoria_spf',
        ),
        migrations.RemoveField(
            model_name='ocorrenciaaeronave',
            name='destino_obs',
        ),
        migrations.RemoveField(
            model_name='ocorrenciaaeronave',
            name='destino_voo',
        ),
        migrations.RemoveField(
            model_name='ocorrenciaaeronave',
            name='fabricante_cenipa',
        ),
        migrations.RemoveField(
            model_name='ocorrenciaaeronave',
            name='fase_voo',
        ),
        migrations.RemoveField(
            model_name='ocorrenciaaeronave',
            name='operacao',
        ),
        migrations.RemoveField(
            model_name='ocorrenciaaeronave',
            name='origem_obs',
        ),
        migrations.RemoveField(
            model_name='ocorrenciaaeronave',
            name='origem_voo',
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Satélite', 'Satélite'), ('Estágio de foguete', 'Estágio de foguete'), ('Cápsula', 'Cápsula'), ('Sonda', 'Sonda')], max_length=25, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='ocorrenciaaeronave',
            name='aeronave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomia.aeronavegeral', verbose_name='Arterfato Espacial'),
        ),
        migrations.AlterField(
            model_name='ocorrenciaaeronave',
            name='observacoes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações adicionais'),
        ),
        migrations.AlterField(
            model_name='ocorrenciaaeronave',
            name='operador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Operador / proprietário'),
        ),
        migrations.AlterField(
            model_name='ocorrenciaaeronave',
            name='operador_detalhe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Detalhes do Operador / proprietário'),
        ),
    ]
