# Generated by Django 5.2 on 2026-01-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0011_remove_ocorrenciaaeronave_alternativa_obs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrenciaaeronave',
            name='custo_reparo',
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='dimensoes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dimensões'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='massa_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Massa total (kg)'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='sistema_comunicacao',
            field=models.TextField(blank=True, null=True, verbose_name='Sistema de Comunicação'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='sistema_controle_atitude',
            field=models.TextField(blank=True, null=True, verbose_name='Sistema de controle de atitude'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='sistema_energia',
            field=models.TextField(blank=True, null=True, verbose_name='Sistema de Energia'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='sistema_navegacao',
            field=models.TextField(blank=True, null=True, verbose_name='Sistema de Navegação'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='sistema_propulsao',
            field=models.TextField(blank=True, null=True, verbose_name='Sistema de propulsão'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='software_bordo',
            field=models.TextField(blank=True, null=True, verbose_name='Software de bordo'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='veiculo_lancador',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Veículo lançador'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='vida_util_prevista',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vida útil prevista'),
        ),
    ]
