# Generated by Django 5.2 on 2026-01-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0012_remove_ocorrenciaaeronave_custo_reparo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciaaeronave',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações adicionais'),
        ),
    ]
