# Generated by Django 5.2 on 2026-01-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0013_alter_ocorrenciaaeronave_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='dados_orbitais_antes_depois',
            field=models.TextField(blank=True, null=True, verbose_name='Dados orbitais antes e depois da ocorrência'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='dados_telemetria_brutos',
            field=models.TextField(blank=True, null=True, verbose_name='Dados de telemetria (brutos)'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='dados_telemetria_processados',
            field=models.TextField(blank=True, null=True, verbose_name='Dados de telemetria (processados)'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='estado_subsistemas_antes_evento',
            field=models.TextField(blank=True, null=True, verbose_name='Estado dos subsistemas antes do evento'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='evidencia_falha',
            field=models.CharField(blank=True, choices=[('MECANICA', 'Mecânica'), ('ELETRICA', 'Elétrica'), ('SOFTWARE', 'Software'), ('OPERACIONAL', 'Operacional'), ('AMBIENTAL', 'Ambiental (radiação, clima espacial)')], max_length=20, null=True, verbose_name='Evidência de falha'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='logs_eventos_falhas',
            field=models.TextField(blank=True, null=True, verbose_name='Logs de eventos e falhas'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='ultimos_comandos_enviados',
            field=models.TextField(blank=True, null=True, verbose_name='Últimos comandos enviados'),
        ),
    ]
