# Generated by Django 5.2 on 2026-01-21 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0014_ocorrenciaaeronave_dados_orbitais_antes_depois_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciadocumento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='ocorrencia/documentos/', verbose_name='Arquivo (upload)'),
        ),
        migrations.AddField(
            model_name='ocorrenciadocumento',
            name='cadastrado_em',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ocorrenciadocumento',
            name='cadastrado_por_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ocorrenciadocumento',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('RELATORIO', 'Relatório'), ('FOTO', 'Foto'), ('VIDEO', 'Vídeo'), ('AUDIO', 'Áudio'), ('LOG', 'Log/Telemetria'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Tipo de documento'),
        ),
    ]
