# Generated by Django 5.2 on 2026-02-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0016_rename_aeronave_to_artefato_espacial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciaaeronave',
            name='danos',
            field=models.CharField(choices=[('DESTRUÍDO', 'DESTRUÍDO'), ('NENHUM DANO', 'NENHUM DANO'), ('PARCIAL', 'PARCIAL'), ('INDETERMINADO', 'INDETERMINADO')], max_length=100, null=True),
        ),
    ]
