# Generated by Django 5.2 on 2026-02-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0017_alter_ocorrenciaaeronave_danos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciageral',
            name='tipo',
            field=models.CharField(choices=[('explosao', 'Explosão'), ('falha_estagio', 'Falha de Estágio'), ('perda_telemetria', 'Perda de Telemetria'), ('falha_motor', 'Falha de Motor'), ('reentrada_nao_controlada', 'Reentrada Não Controlada'), ('colisao_orbital', 'Colisão Orbital'), ('outro', 'Outro')], max_length=50, null=True, verbose_name='tipo'),
        ),
    ]
