# Generated by Django 5.2 on 2026-02-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0018_alter_ocorrenciageral_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaAutenticar',
            fields=[
            ],
            options={
                'verbose_name': 'Autenticar Ocorrência',
                'verbose_name_plural': 'Autenticar Ocorrências',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ocorrencia.ocorrenciageral',),
        ),
        migrations.CreateModel(
            name='OcorrenciaConfirmar',
            fields=[
            ],
            options={
                'verbose_name': 'Confirmar Ocorrência',
                'verbose_name_plural': 'Confirmar Ocorrências',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ocorrencia.ocorrenciageral',),
        ),
        migrations.CreateModel(
            name='OcorrenciaRedigir',
            fields=[
            ],
            options={
                'verbose_name': 'Redigir Ocorrência',
                'verbose_name_plural': 'Redigir Ocorrências',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ocorrencia.ocorrenciageral',),
        ),
        migrations.AddField(
            model_name='ocorrenciaaeronave',
            name='fase_missao',
            field=models.CharField(blank=True, choices=[('PREPARACAO', 'Preparação'), ('ABASTECIMENTO', 'Abastecimento'), ('CONTAGEM_REGRESSIVA', 'Contagem regressiva'), ('LANCAMENTO', 'Lançamento'), ('VOO_PROPULSADO', 'Voo propulsado'), ('SEPARACAO_ESTAGIOS', 'Separação de estágios'), ('ORBITA', 'Órbita'), ('REENTRADA', 'Reentrada')], max_length=50, null=True, verbose_name='Fase da Missão'),
        ),
    ]
