# Generated by Django 5.2 on 2026-02-19 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0020_ocorrenciaconfirmacao_usuario_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciaautenticacao',
            name='data_autenticacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da autenticação'),
        ),
        migrations.AddField(
            model_name='ocorrenciaautenticacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autenticado por'),
        ),
    ]
