# Generated by Django 5.2 on 2026-02-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0021_ocorrenciaautenticacao_usuario_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciaautenticacao',
            name='data_autenticacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da autenticação'),
        ),
    ]
