# Generated by Django 5.2 on 2026-02-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0022_ocorrenciaautenticacao_data_datefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciaconfirmacao',
            name='data_confirmacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da confirmação'),
        ),
    ]
