# Generated by Django 5.2 on 2026-02-20 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0023_ocorrenciaconfirmacao_data_datefield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocorrenciacomissao',
            options={'ordering': ['id'], 'verbose_name': 'Membro da Comissão', 'verbose_name_plural': 'Comissão de Investigação'},
        ),
        migrations.AddField(
            model_name='ocorrenciacomissao',
            name='funcao',
            field=models.CharField(blank=True, choices=[('ASPECTO_OPERACIONAL', 'ASPECTO OPERACIONAL'), ('ASPECTO_MATERIAL', 'ASPECTO MATERIAL'), ('ASPECTO_MEDICO', 'ASPECTO MÉDICO'), ('ASPECTO_PSICOLOGICO', 'ASPECTO PSICOLÓGICO'), ('INVESTIGADOR_ENCARREGADO', 'INVESTIGADOR ENCARREGADO')], max_length=50, null=True, verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='ocorrenciacomissao',
            name='investigador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Investigador'),
        ),
        migrations.AddField(
            model_name='ocorrenciacomissao',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.DeleteModel(
            name='OcorrenciaRegistroRp',
        ),
    ]
