# Generated by Django 5.2 on 2026-02-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0024_ocorrenciacomissao_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciacomissao',
            name='observacoes',
            field=models.CharField(max_length=200, null=True, verbose_name='Observações'),
        ),
    ]
