# Generated by Django 5.2 on 2026-02-23 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0025_alter_ocorrenciacomissao_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaInvestigada',
            fields=[
            ],
            options={
                'verbose_name': 'Controle de Investigação',
                'verbose_name_plural': 'Controle de Investigação',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ocorrencia.ocorrenciageral',),
        ),
    ]
