# Generated by Django 5.2 on 2026-02-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0026_ocorrenciainvestigada_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciacontrole',
            name='fase_atual',
            field=models.CharField(blank=True, choices=[('RAI', 'RAI'), ('INVESTIGACAO', 'INVESTIGAÇÃO'), ('ELABORACAO_RELATORIO', 'ELABORAÇÃO DO RELATÓRIO'), ('REVISAO', 'REVISÃO'), ('PUBLICADO', 'PUBLICADO')], default='RAI', max_length=30, null=True, verbose_name='Fase atual'),
        ),
        migrations.AddField(
            model_name='ocorrenciacontrole',
            name='numero_relatorio',
            field=models.CharField(blank=True, default='A DEFINIR', max_length=100, null=True, verbose_name='Número do Relatório'),
        ),
        migrations.AddField(
            model_name='ocorrenciacontrole',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='ocorrenciacontrole',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('1', '1 - URGENTE'), ('2', '2 - ALTA'), ('3', '3 - MÉDIA'), ('4', '4 - NORMAL'), ('5', '5 - BAIXA')], default='4', max_length=1, null=True, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='ocorrenciacontrole',
            name='situacao_investigacao',
            field=models.CharField(blank=True, choices=[('ATIVA', 'ATIVA'), ('SUSPENSA', 'SUSPENSA'), ('ENCERRADA', 'ENCERRADA'), ('ARQUIVADA', 'ARQUIVADA')], default='ATIVA', max_length=20, null=True, verbose_name='Situação da Investigação'),
        ),
        migrations.AddField(
            model_name='ocorrenciacontrole',
            name='tipo_relatorio',
            field=models.CharField(blank=True, choices=[('RAI', 'RAI - Relatório de Ação Inicial'), ('AERF', 'AERF - Relatório Final de Acidente'), ('INCF', 'INCF - Relatório Final de Incidente'), ('INGF', 'INGF - Relatório Final de Incidente Grave'), ('RELPREV', 'RELPREV - Relatório de Prevenção'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Tipo de Relatório a Produzir'),
        ),
        migrations.AlterField(
            model_name='ocorrenciacontrole',
            name='orgao_investigador',
            field=models.CharField(choices=[('CENIPA', 'CENIPA'), ('OUTRO', 'OUTRO')], max_length=25, null=True, verbose_name='Órgão Investigador'),
        ),
    ]
