# Generated by Django 5.2 on 2026-02-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0027_ocorrenciacontrole_novos_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciacontrole',
            name='fase_atual',
            field=models.CharField(blank=True, choices=[('RAI', 'RAI'), ('MIN', 'MINUTA'), ('REV', 'REVISAO'), ('RF', 'RF'), ('FIM', 'FIM')], default='RAI', max_length=30, null=True, verbose_name='Fase atual'),
        ),
        migrations.AlterField(
            model_name='ocorrenciacontrole',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('1', '1 - CENIPA'), ('2', '2 - ALTISSÍMA'), ('3', '3 - ALTA'), ('4', '4 - MÉDIA'), ('5', '5 - NORMAL')], default='4', max_length=1, null=True, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='ocorrenciacontrole',
            name='situacao_investigacao',
            field=models.CharField(blank=True, choices=[('ATIVA', 'ATIVA'), ('FINALIZADA', 'FINALIZADA')], default='ATIVA', max_length=20, null=True, verbose_name='Situação da Investigação'),
        ),
        migrations.AlterField(
            model_name='ocorrenciacontrole',
            name='tipo_relatorio',
            field=models.CharField(blank=True, choices=[('RF', 'RF'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Tipo de Relatório a Produzir'),
        ),
        migrations.AlterField(
            model_name='ocorrenciadocumento',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('ARTEFATO_MAPA_COMPONENTES', 'Artefato Espacial - Mapa de Componentes'), ('ARTEFATO_SISTEMAS_SUBSISTEMAS', 'Artefato Espacial - Sistemas e Subsistemas'), ('ARTEFATO_MASSA_CG', 'Artefato Espacial - Massa e Centro de Gravidade'), ('ARTEFATO_SEGURO', 'Artefato Espacial - Seguro Espacial'), ('ARTEFATO_STATUS_AEB', 'Artefato Espacial - Status AEB'), ('ARTEFATO_CERTIFICACOES', 'Artefato Espacial - Certificações e Autorizações'), ('ARTEFATO_TERMO_LIBERACAO', 'Artefato Espacial - Termo de Liberação para Lançamento'), ('ARTEFATO_OUTROS', 'Artefato Espacial - Outros Documentos'), ('IMAGEM_ACAO_INICIAL', 'Imagens - Ação Inicial'), ('IMAGEM_CROQUI', 'Imagens - Croqui do Sítio de Lançamento'), ('IMAGEM_OUTRAS', 'Imagens - Outras'), ('LAUDO_TECNICO', 'Laudos Técnicos e Resultados'), ('PORTARIA_COMISSAO', 'Portaria de Designação de Comissão de Investigação'), ('COORDENADOR_INVESTIGACAO', 'Coordenador da Investigação'), ('RESPONSAVEL_COLETA_DADOS', 'Responsável pela Coleta de Dados'), ('VEICULO_STATUS', 'Veículo Lançador - Status Regulatório'), ('OPERADOR_STATUS', 'Operador Espacial - Status Regulatório'), ('OPERADOR_OUTROS', 'Operador Espacial - Outros Documentos'), ('OUTROS_DOCUMENTOS', 'Outros Documentos Gerais')], max_length=120, null=True, verbose_name='Tipo de documento'),
        ),
    ]
