# Generated by Django 5.2 on 2026-02-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0028_alter_ocorrenciacontrole_fase_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciadocumento',
            name='arquivo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='ocorrencia/documentos/', verbose_name='Arquivo (upload)'),
        ),
    ]
