# Generated by Django 5.2 on 2026-02-24 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0029_ocorrenciadocumento_arquivo_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='ocorrenciarevisaoseripa',
                    name='ocorrencia',
                ),
            ],
        ),
        migrations.AddField(
            model_name='ocorrenciarevisaorelatorio',
            name='cadastrado_em',
            field=models.DateField(blank=True, null=True, verbose_name='Cadastrado Em'),
        ),
        migrations.AddField(
            model_name='ocorrenciarevisaorelatorio',
            name='cadastrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencia_revisao_relatorio_cadastrado_por', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por'),
        ),
        migrations.AddField(
            model_name='ocorrenciarevisaorelatorio',
            name='data_atribuicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Atribuição'),
        ),
        migrations.AddField(
            model_name='ocorrenciarevisaorelatorio',
            name='setor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='ocorrenciageral',
            name='numero_processo',
            field=models.CharField(max_length=100, null=True, verbose_name='Número do Processo'),
        ),
        migrations.AlterField(
            model_name='ocorrenciageral',
            name='publico',
            field=models.BooleanField(null=True, verbose_name='Público nos Painéis'),
        ),
        migrations.AlterField(
            model_name='ocorrenciageral',
            name='status',
            field=models.CharField(max_length=50, null=True, verbose_name='Status da Ocorrência'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='OcorrenciaRevisaoRsv'),
                migrations.DeleteModel(name='OcorrenciaRevisaoSeripa'),
            ],
        ),
    ]
