# Generated by Django 5.2 on 2026-02-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0031_ocorrenciarevisaorf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OcorrenciaRevisaoRF',
        ),
    ]
