# Generated by Django 5.2 on 2026-02-24 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0032_delete_ocorrenciarevisaorf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocorrenciarevisaorelatorio',
            options={'ordering': ['id'], 'verbose_name': 'Painel de Revisão RF', 'verbose_name_plural': 'Painel de Revisão RF'},
        ),
        migrations.AddField(
            model_name='ocorrenciarevisaorelatorio',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='revisao_relatorio/anexos/', verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='ocorrenciarevisaorelatorio',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencia_revisao_relatorio_revisor', to=settings.AUTH_USER_MODEL, verbose_name='Revisor'),
        ),
    ]
