# Generated by Django 5.2 on 2026-02-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0033_alter_ocorrenciarevisaorelatorio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciarevisaorelatorio',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
