# Generated by Django 5.2 on 2026-02-24 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0034_ocorrenciarevisaorelatorio_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaRevisaoRF',
            fields=[
            ],
            options={
                'verbose_name': 'Painel de Revisão RF',
                'verbose_name_plural': 'Painel de Revisão RF',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ocorrencia.ocorrenciageral',),
        ),
    ]
