# Generated by Django 5.2 on 2026-02-24 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0035_ocorrenciarevisaorf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OcorrenciaRevisaoRF',
        ),
    ]
