# Generated by Django 5.2 on 2026-03-19 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0036_delete_ocorrenciarevisaorf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocorrenciaasoaci',
            options={'ordering': ['id'], 'verbose_name_plural': 'Representante Acreditado'},
        ),
        migrations.AddField(
            model_name='ocorrenciaasoaci',
            name='destino_notificacao',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Nome do Representante'),
        ),
        migrations.AddField(
            model_name='ocorrenciaasoaci',
            name='dia_envio_notificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Notificação'),
        ),
        migrations.AddField(
            model_name='ocorrenciaasoaci',
            name='initial_notification',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='NÃO', max_length=30, null=True, verbose_name='Initial Notification'),
        ),
        migrations.AddField(
            model_name='ocorrenciaasoaci',
            name='nome_rep_acred',
            field=models.TextField(blank=True, null=True, verbose_name='Nome do Representante'),
        ),
        migrations.AddField(
            model_name='ocorrenciaasoaci',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='ocorrenciaasoaci',
            name='tem_rep_acred',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO'), ('DESCONHECIDO', 'DESCONHECIDO')], default='NÃO', max_length=30, null=True, verbose_name='Tem Rep Acred?'),
        ),
        migrations.AlterField(
            model_name='ocorrenciarevisaorelatorio',
            name='data_atribuicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Atribuição'),
        ),
        migrations.AlterField(
            model_name='ocorrenciarevisaorelatorio',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencia_revisao_relatorio_revisor', to=settings.AUTH_USER_MODEL, verbose_name='Revisor Responsável'),
        ),
        migrations.AlterField(
            model_name='ocorrenciarevisaorelatorio',
            name='setor',
            field=models.CharField(blank=True, choices=[('DESIGNACAO', 'Designação'), ('REVISAO_PRELIMINAR_FATOR_OPERACIONAL', 'Revisão Preliminar/Fator Operacional'), ('REVISAO_FATOR_HUMANO', 'Revisão Fator Humano'), ('REVISAO_FATOR_MATERIAL', 'Revisão Fator Material'), ('RECOMENDACAO_DE_SEGURANCA', 'Recomendação de Segurança'), ('JEDI', 'JEDI'), ('REVISAO_GRAMATICAL', 'Revisão Gramatical'), ('REVISAO_FINAL', 'Revisão Final'), ('APRECIACAO_CHEFE_DIP', 'Apreciação Chefe DIP'), ('APRECIACAO_CHEFE_DO_CENIPA', 'Apreciação Chefe do CENIPA'), ('CONTROLE_IMPRESSAO', 'Controle/Impressão'), ('TRADUCAO', 'Tradução'), ('ASOACI', 'ASOACI'), ('VALIDACAO_DE_DADOS', 'Validação de Dados'), ('DIVULGACAO', 'Divulgação'), ('ASSINATURA_CHEFE_DO_CENIPA', 'Assinatura Chefe do CENIPA'), ('ARQUIVO', 'Arquivo'), ('REABERTURA', 'Reabertura')], max_length=150, null=True, verbose_name='Setor Responsável'),
        ),
    ]
