# Generated by Django 5.2 on 2026-03-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0037_alter_ocorrenciaasoaci_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciaasoaci',
            name='nome_rep_acred',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Nome do Representante'),
        ),
    ]
