# Generated by Django 5.2 on 2026-03-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0038_alter_ocorrenciaasoaci_nome_rep_acred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciaasoaci',
            name='destino_notificacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Destinatário/Instituição'),
        ),
        migrations.AlterField(
            model_name='ocorrenciaasoaci',
            name='nome_rep_acred',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Representante'),
        ),
    ]
