# Generated by Django 5.2 on 2026-03-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0040_ocorrenciarelatorio_campos_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciaasoaci',
            name='tem_rep_acred',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO'), ('AGUARDANDO', 'AGUARDANDO')], default='NÃO', max_length=30, null=True, verbose_name='Tem Rep Acred?'),
        ),
        migrations.AlterField(
            model_name='ocorrenciageral',
            name='classificacao',
            field=models.CharField(choices=[('ACIDENTE', 'ACIDENTE'), ('INCIDENTE', 'INCIDENTE'), ('INFORTÚNIO', 'INFORTÚNIO')], max_length=50, null=True, verbose_name='Classificação'),
        ),
    ]
