# Generated by Django 4.2 on 2024-11-19 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeografiaPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, null=True)),
                ('nome_codigo', models.CharField(max_length=50, null=True)),
                ('idioma_codigo', models.CharField(max_length=10, null=True)),
                ('continente', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'geografia_pais',
            },
        ),
        migrations.CreateModel(
            name='GeografiaUf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, null=True)),
                ('nome_codigo', models.CharField(max_length=10, null=True)),
                ('regiao', models.CharField(max_length=50, null=True)),
                ('comar', models.CharField(max_length=50, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomia.geografiapais')),
            ],
            options={
                'db_table': 'geografia_uf',
            },
        ),
        migrations.CreateModel(
            name='GeografiaCidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
                ('altitude', models.CharField(max_length=100, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomia.geografiapais')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomia.geografiauf')),
            ],
            options={
                'db_table': 'geografia_cidade',
            },
        ),
        migrations.CreateModel(
            name='AerodromoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(max_length=7, null=True)),
                ('iata', models.CharField(max_length=5, null=True)),
                ('nome', models.CharField(max_length=150, null=True)),
                ('propriedade', models.CharField(max_length=150, null=True)),
                ('tipo', models.CharField(max_length=10, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
                ('latitude_decimal', models.CharField(max_length=100, null=True)),
                ('longitude_decimal', models.CharField(max_length=100, null=True)),
                ('altitude', models.CharField(max_length=100, null=True)),
                ('vfr_diurno', models.CharField(max_length=100, null=True)),
                ('vfr_noturno', models.CharField(max_length=100, null=True)),
                ('ifr_diurno', models.CharField(max_length=100, null=True)),
                ('ifr_noturno', models.CharField(max_length=100, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomia.geografiacidade')),
            ],
            options={
                'db_table': 'aerodromo_geral',
            },
        ),
    ]
