# Generated by Django 4.2 on 2024-11-19 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AeronaveGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, null=True)),
                ('nacionalidade_registro', models.CharField(max_length=50, null=True)),
                ('nacionalidade_fabricacao', models.CharField(max_length=50, null=True)),
                ('nacionalidade_projeto', models.CharField(max_length=50, null=True)),
                ('ano_fabricacao', models.DateField(default=datetime.date.today)),
                ('classificacao', models.CharField(max_length=50, null=True)),
                ('equipamento', models.CharField(max_length=50, null=True)),
                ('fabricante_codigo', models.CharField(max_length=50, null=True)),
                ('fabricante_nome', models.CharField(max_length=70, null=True)),
                ('modelo', models.CharField(max_length=50, null=True)),
                ('classe', models.CharField(max_length=50, null=True)),
                ('tipo_icao', models.CharField(max_length=50, null=True)),
                ('habilitacao', models.CharField(max_length=50, null=True)),
                ('tipo_motor', models.CharField(max_length=50, null=True)),
                ('quantidade_motor', models.IntegerField(null=True)),
                ('tipo_trem_pouso', models.CharField(max_length=50, null=True)),
                ('numero_assentos', models.IntegerField(null=True)),
                ('numero_serie', models.IntegerField(null=True)),
                ('passageiros_maximo', models.IntegerField(null=True)),
                ('peso_max_decolagem', models.IntegerField(null=True)),
                ('tripulacao_minima', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'aeronave_geral',
            },
        ),
    ]
