# Generated by Django 4.2 on 2024-11-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomia', '0002_aeronavegeral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronavegeral',
            name='classificacao',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
