# Generated by Django 4.2 on 2024-11-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomia', '0003_alter_aeronavegeral_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronavegeral',
            name='ano_fabricacao',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='aeronavegeral',
            name='classificacao',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
