# Generated by Django 4.2 on 2024-11-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomia', '0004_alter_aeronavegeral_ano_fabricacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronavegeral',
            name='numero_serie',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
