# Generated by Django 4.2 on 2024-11-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomia', '0005_alter_aeronavegeral_numero_serie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aeronavegeral',
            options={'ordering': ['modelo'], 'verbose_name': 'Aeronave Geral'},
        ),
    ]
