# Generated by Django 5.2 on 2026-02-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomia', '0006_alter_aeronavegeral_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronavegeral',
            name='matricula',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
