# Generated by Django 5.2 on 2026-02-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomia', '0009_delete_aeronavegeral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculolancador',
            name='propelente',
            field=models.JSONField(blank=True, null=True, verbose_name='Propelente'),
        ),
    ]
