"""
Django settings for dedalo project.

Generated by 'django-admin startproject' using Django 4.2.
Updated to Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.urls import reverse_lazy
from django.templatetags.static import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-w27i$p27d&@^wr(9c@(gzp0r424qgpj5(07j$wmm*+yx-m1186')

DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')

CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'unfold',  # Django Unfold - deve vir ANTES de django.contrib.admin
    'unfold.contrib.filters',  # Filtros avançados do Unfold
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # django custom
    'rangefilter',  # Mantido - pode ser usado junto com Unfold
    'nested_admin',  # Para nested inlines (tripulantes, lesões, labdata dentro de aeronave)
    'crispy_forms',
    'crispy_bootstrap5',
    'auditlog',
    'rest_framework',
    'django_filters',
    'drf_spectacular',

    # Apps
    'usuario',
    'ocorrencia',
    'labdata',
    'material_apoio',
    'mensagem',
    'taxonomia',
    'api',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'usuario.middleware.TOTPRequiredMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dedalo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dedalo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'orion_django'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': int(os.environ.get('DB_PORT', 3306)),
        'OPTIONS': {
            'charset': 'utf8mb4'
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "usuario.User"

# Django REST Framework
# API pensada para consumo same-origin (nginx proxy /api/ -> web) via
# sessão/cookie, igual ao admin hoje. Sem CORS/JWT: ver plano de migração
# para Next.js (docs/nextjs-migration-plan, se existir) para o racional.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'api.permissions.DjangoModelPermissionsWithView',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Áquila API',
    'DESCRIPTION': 'API do Sistema de Gestão de Ocorrências Espaciais (CENIPA)',
    'VERSION': '0.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = ('bootstrap5', 'unfold_crispy')
CRISPY_TEMPLATE_PACK = 'unfold_crispy'


# Django Unfold Configuration
# https://unfoldadmin.com/docs/configuration/
UNFOLD = {
    "SITE_TITLE": "ÁQUILA",
    "SITE_HEADER": "ÁQUILA",
    "SITE_SUBHEADER": "Sistema de Gestão de Ocorrências Espaciais",
    "DASHBOARD_CALLBACK": "dedalo.views.dashboard_callback",
    "ENVIRONMENT": "dedalo.settings.environment_callback",
    "SITE_DROPDOWN": [
        {
            "icon": "diamond",
            "title": "My site",
            "link": "https://example.com",
        },
    ],
    "SITE_URL": "/",
    "SITE_SYMBOL": "rocket",  # Ícone de avião (Material Symbols)
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "BORDER_RADIUS": "6px",
    "COMMAND": {
        "search_models": ['ocorrencia.OcorrenciaGeral'],  # Default: False
        "search_callback": "utils.search_callback",
        "show_history": True,  # Enable history
        "search_fields": ['ocorrencia.OcorrenciaGeral.id']
    },
    "COLORS": {
        "base": {
            "50": "oklch(98.5% .002 247.839)",
            "100": "oklch(96.7% .003 264.542)",
            "200": "oklch(92.8% .006 264.531)",
            "300": "oklch(87.2% .01 258.338)",
            "400": "oklch(70.7% .022 261.325)",
            "500": "oklch(55.1% .027 264.364)",
            "600": "oklch(44.6% .03 256.802)",
            "700": "oklch(37.3% .034 259.733)",
            "800": "oklch(27.8% .033 256.848)",
            "900": "oklch(21% .034 264.665)",
            "950": "oklch(13% .028 261.692)",
        },
        "primary": {
            "50": "oklch(97.0% .015 262.9)",
            "100": "oklch(93.5% .040 262.9)",
            "200": "oklch(88.5% .080 262.9)",
            "300": "oklch(81.0% .130 262.9)",
            "400": "oklch(71.0% .180 262.9)",
            "500": "oklch(58.5% .216 262.9)",
            "600": "oklch(52.0% .200 262.9)",
            "700": "oklch(45.5% .180 262.9)",
            "800": "oklch(38.0% .150 262.9)",
            "900": "oklch(31.0% .120 262.9)",
            "950": "oklch(23.0% .090 262.9)",
        },
        "font": {
            "subtle-light": "var(--color-base-500)",  # text-base-500
            "subtle-dark": "var(--color-base-400)",  # text-base-400
            "default-light": "var(--color-base-600)",  # text-base-600
            "default-dark": "var(--color-base-300)",  # text-base-300
            "important-light": "var(--color-base-900)",  # text-base-900
            "important-dark": "var(--color-base-100)",  # text-base-100
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "command_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Navegação",
                "items": [
                    {
                        "title": "Home",
                        "icon": "home",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": "Redigir/Autenticar",
                "collapsible": True,
                "icon": "edit",
                "items": [
                    {
                        "title": "Redigir",
                        "icon": "description",
                        "link": reverse_lazy("admin:ocorrencia_ocorrenciaredigir_add"),
                        "permission": lambda request: request.user.has_perm("ocorrencia.add_ocorrenciageral"),
                    },
                    {
                        "title": "Confirmar",
                        "icon": "check_circle",
                        "link": reverse_lazy("admin:ocorrencia_ocorrenciaconfirmar_changelist"),
                        "permission": lambda request: request.user.has_perm("ocorrencia.change_ocorrenciageral"),
                    },
                    {
                        "title": "Autenticar",
                        "icon": "verified",
                        "link": reverse_lazy("admin:ocorrencia_ocorrenciaautenticar_changelist"),
                        "permission": lambda request: request.user.has_perm("ocorrencia.change_ocorrenciageral"),
                    },
                ],
            },
            {
                "title": "Ocorrências",
                "collapsible": True,
                "icon": "warning",
                "items": [
                    {
                        "title": "Ocorrências Gerais",
                        "icon": "description",
                        "link": reverse_lazy("admin:ocorrencia_ocorrenciageral_changelist"),
                        "permission": lambda request: request.user.has_perm("ocorrencia.view_ocorrenciageral"),
                    },
                     {
                        "title": "Painel de Revisão RF",
                        "icon": "description",
                        "link": reverse_lazy("admin:ocorrencia_ocorrenciarevisaorelatorio_changelist"),
                        "permission": lambda request: request.user.has_perm("ocorrencia.view_ocorrenciarevisaorelatorio"),
                    },
                ],
            },
            {
                "title": "Controle e gestão",
                "collapsible": True,
                "icon": "task_alt",
                "items": [
                    {
                        "title": "Controle da Investigação",
                        "icon": "manage_search",
                        "link": reverse_lazy("admin:ocorrencia_ocorrenciainvestigada_changelist"),
                        "permission": lambda request: request.user.has_perm("ocorrencia.view_ocorrenciacontrole"),
                    },
                ],
            },
           
            {
                "title": "Material de Apoio",
                "collapsible": True,
                "icon": "menu_book",
                "items": [
                    {
                        "title": "Formulários",
                        "icon": "assignment",
                        "link": reverse_lazy("admin:material_apoio_formulario_changelist"),
                        "permission": lambda request: request.user.has_perm("material_apoio.view_formulario"),
                    },
                    {
                        "title": "Normas e Legislações",
                        "icon": "gavel",
                        "link": reverse_lazy("admin:material_apoio_normalegislacao_changelist"),
                        "permission": lambda request: request.user.has_perm("material_apoio.view_normalegislacao"),
                    },
                    {
                        "title": "Documentos Diversos",
                        "icon": "folder_open",
                        "link": reverse_lazy("admin:material_apoio_documentodiverso_changelist"),
                        "permission": lambda request: request.user.has_perm("material_apoio.view_documentodiverso"),
                    },
                    {
                        "title": "Investigações de Outras Autoridades",
                        "icon": "travel_explore",
                        "link": reverse_lazy("admin:material_apoio_investigacaooutrasautoridades_changelist"),
                        "permission": lambda request: request.user.has_perm("material_apoio.view_investigacaooutrasautoridades"),
                    },
                ],
            },
             {
                "title": "Taxonomia",
                "collapsible": True,
                "icon": "category",
                "items": [
                    {
                        "title": "Veículos Lançadores",
                        "icon": "rocket_launch",
                        "link": reverse_lazy("admin:taxonomia_veiculolancador_changelist"),
                        "permission": lambda request: request.user.has_perm("taxonomia.view_veiculolancador"),
                    },
                    {
                        "title": "Artefatos Espaciais",
                        "icon": "satellite_alt",
                        "link": reverse_lazy("admin:taxonomia_artefatoespacial_changelist"),
                        "permission": lambda request: request.user.has_perm("taxonomia.view_artefatoespacial"),
                    },
                     {
                        "title": "Centros de Lançamento",
                        "icon": "connecting_airports",
                        "link": reverse_lazy("admin:taxonomia_aerodromogeral_changelist"),
                        "permission": lambda request: request.user.has_perm("taxonomia.view_aerodromogeral"),
                    },
                    {
                        "title": "Cidades",
                        "icon": "location_city",
                        "link": reverse_lazy("admin:taxonomia_geografiacidade_changelist"),
                        "permission": lambda request: request.user.has_perm("taxonomia.view_geografiacidade"),
                    },
                    {
                        "title": "Países",
                        "icon": "public",
                        "link": reverse_lazy("admin:taxonomia_geografiapais_changelist"),
                        "permission": lambda request: request.user.has_perm("taxonomia.view_geografiapais"),
                    },
                    {
                        "title": "UFs",
                        "icon": "map",
                        "link": reverse_lazy("admin:taxonomia_geografiauf_changelist"),
                        "permission": lambda request: request.user.has_perm("taxonomia.view_geografiauf"),
                    },
                   
                ],
            },
            {
                "title": "Usuários & Grupos",
                "collapsible": True,
                "icon": "admin_panel_settings",
                "items": [
                    {
                        "title": "Usuários",
                        "icon": "person",
                        "link": reverse_lazy("admin:usuario_user_changelist"),
                        "permission": lambda request: request.user.has_perm("usuario.view_user"),
                    },
                    {
                        "title": "Grupos",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.has_perm("auth.view_group"),
                    },
                ],
            },

        ],
    },
    "TABS": [
        {
            "models": [
            {"name": "ocorrencia.ocorrenciageral", "detail": True},
            {"name": "ocorrencia.ocorrenciainvestigada", "detail": True},
        ],
            "items": [
                {"title": "INFORMAÇÕES GERAIS", "link": "", "inline": "general"},
                {"title": "ARTEFATO ESPACIAL", "link": "", "inline": "ocorrencia_aeronave"},
                {"title": "CONTROLE", "link": "", "inline": "controle"},
                {"title": "GESTÃO", "link": "", "inline": "ocorrencia_controle"},
                {"title": "DOCUMENTOS", "link": "", "inline": "ocorrencia_documento"},               
            #    {"title": "LABDATA", "link": "", "inline": "ocorrencia_labdata"},
                {"title": "INTERNACIONAL", "link": "", "inline": "ocorrencia_asoaci"},
                {"title": "DIVULGAÇÃO", "link": "", "inline": "ocorrencia_relatorio"},
                {"title": "REVISÃO RELATÓRIO", "link": "", "inline": "ocorrencia_revisao_relatorio"}
            ],
        },
    ],
    # "ENVIRONMENT": None,  # Pode ser configurado depois se necessário
    # "DASHBOARD_CALLBACK": None,  # Pode ser configurado depois para dashboard customizado
    # "LOGIN": {
    #     "image": None,
    #     "redirect_after": None,
    # },
    "STYLES": [lambda request: static("css/nav.css")],
    # "SCRIPTS": [],
}

def environment_callback(request):
    """
    Callback has to return a list of two values represeting text value and the color
    type of the label displayed in top right corner.
    """
    return ["Production", "success"] # info, danger, warning, success


# help na hora que o bicho pega: usar para reiniciar os migrates usar o --fake
# py manage.py migrate --fake-initial 