# Generated by Django 4.2 on 2024-11-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=150)),
                ('nome_guerra', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_access', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.TextField(default='/media/avatars/default-avatar.png')),
                ('posto_graduacao', models.CharField(choices=[('SO', 'SO'), ('CV', 'CV'), ('1S', '1S'), ('2S', '2S'), ('3S', '3S')], max_length=10, null=True)),
                ('hierarquia_posto_graduacao', models.IntegerField(null=True)),
                ('credencial', models.CharField(max_length=50)),
                ('qualificacao', models.CharField(max_length=50)),
                ('local_trabalho', models.CharField(max_length=50)),
                ('telefone', models.IntegerField(null=True)),
                ('cpf', models.IntegerField(null=True)),
                ('investigador', models.IntegerField(null=True)),
                ('ojt', models.TextField(null=True)),
                ('trilha_capacitacao', models.TextField(null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
