# Generated by Django 4.2 on 2024-11-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credencial',
            field=models.CharField(max_length=100),
        ),
    ]
