# Generated by Django 4.2 on 2024-11-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_user_credencial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='local_trabalho',
            field=models.CharField(choices=[('CENIPA', 'CENIPA'), ('SERIPA 1', 'SERIPA 1'), ('SERIPA 2', 'SERIPA 2'), ('SERIPA 3', 'SERIPA 3'), ('SERIPA 4', 'SERIPA 4'), ('SERIPA 5', 'SERIPA 5')], max_length=50),
        ),
    ]
