# Generated by Django 5.2 on 2026-02-10 14:20

from django.db import migrations


def set_staff_for_superusers(apps, schema_editor):
    User = apps.get_model('usuario', 'User')
    User.objects.filter(is_superuser=True).update(is_staff=True)


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_user_groups_user_is_staff_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RunPython(set_staff_for_superusers, migrations.RunPython.noop),
    ]
