# Generated by Django 5.2 on 2026-02-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_set_staff_for_superusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='credencial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='hierarquia_posto_graduacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='investigador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='local_trabalho',
            field=models.CharField(choices=[('CENIPA', 'CENIPA'), ('SERIPA 1', 'SERIPA 1'), ('SERIPA 2', 'SERIPA 2'), ('SERIPA 3', 'SERIPA 3'), ('SERIPA 4', 'SERIPA 4'), ('SERIPA 5', 'SERIPA 5'), ('SERIPA 6', 'SERIPA 6'), ('SERIPA 7', 'SERIPA 7'), ('DCTA', 'DCTA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='ojt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='posto_graduacao',
            field=models.CharField(choices=[('MB', 'Major-Brigadeiro'), ('BR', 'Brigadeiro'), ('CEL', 'Coronel'), ('TC', 'Tenente-Coronel'), ('MAJ', 'Major'), ('CAP', 'Capitão'), ('1T', '1º Tenente'), ('2T', '2º Tenente'), ('ASP', 'Aspirante a Oficial'), ('SO', 'Suboficial'), ('1S', '1º Sargento'), ('2S', '2º Sargento'), ('3S', '3º Sargento'), ('CB', 'Cabo'), ('CV', 'CIVIL')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qualificacao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='trilha_capacitacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
