# Generated by Django 5.2 on 2026-04-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_totp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_obrigatorio',
            field=models.BooleanField(default=False, verbose_name='2FA obrigatório'),
        ),
    ]
