# Generated by Django 5.2 on 2026-02-19 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('categoria', models.CharField(choices=[('NORMA', 'Norma'), ('LEGISLACAO', 'Legislação'), ('MANUAL', 'Manual'), ('PROCEDIMENTO', 'Procedimento'), ('INSTRUCAO', 'Instrução'), ('REGULAMENTO', 'Regulamento'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Categoria')),
                ('tipo_documento', models.CharField(choices=[('ICA', 'ICA - Instrução do Comando da Aeronáutica'), ('NSCA', 'NSCA - Norma do Sistema do Comando da Aeronáutica'), ('MCA', 'MCA - Manual do Comando da Aeronáutica'), ('RBAC', 'RBAC - Regulamento Brasileiro da Aviação Civil'), ('PORTARIA', 'Portaria'), ('RESOLUCAO', 'Resolução'), ('CIRCULAR', 'Circular'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Documento')),
                ('numero_norma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número da Norma')),
                ('divisao_responsavel', models.CharField(blank=True, max_length=200, null=True, verbose_name='Divisão Responsável')),
                ('setor_responsavel', models.CharField(blank=True, max_length=200, null=True, verbose_name='Setor Responsável')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data da Emissão')),
                ('data_efetivacao', models.DateField(blank=True, null=True, verbose_name='Data da Efetivação')),
                ('data_aprovacao', models.DateField(blank=True, null=True, verbose_name='Data da Aprovação')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data da Publicação')),
                ('documento_word', models.FileField(blank=True, null=True, upload_to='material_apoio/word/', verbose_name='Documento Word')),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='material_apoio/pdf/', verbose_name='Documento PDF')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('pessoa_responsavel', models.ForeignKey(blank=True, help_text='Pessoa responsável pela manutenção deste documento.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Pessoa Responsável')),
            ],
            options={
                'verbose_name': 'Material de Apoio',
                'verbose_name_plural': 'Materiais de Apoio',
                'db_table': 'material_apoio',
                'ordering': ['titulo'],
            },
        ),
    ]
