# Generated by Django 5.2 on 2026-02-19 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_apoio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialapoio',
            name='cadastrado_em',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Cadastrado em'),
        ),
        migrations.AddField(
            model_name='materialapoio',
            name='cadastrado_por_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiais_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por'),
        ),
        migrations.AlterField(
            model_name='materialapoio',
            name='tipo_documento',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('COMUNICACAO', 'Comunicação'), ('IS', 'Is'), ('AUTO', 'Auto'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Documento'),
        ),
    ]
