# Generated by Django 5.2 on 2026-03-21 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_apoio', '0002_materialapoio_cadastrado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigacaoOutrasAutoridades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('autoridade_investigadora', models.CharField(help_text='Ex: NTSB, BEA, AAIB, TSB, DGAC', max_length=200, verbose_name='Autoridade Investigadora')),
                ('numero_relatorio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Relatório')),
                ('tipo_ocorrencia', models.CharField(choices=[('ACIDENTE', 'Acidente'), ('INCIDENTE_GRAVE', 'Incidente Grave'), ('INCIDENTE', 'Incidente'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Ocorrência')),
                ('data_ocorrencia', models.DateField(blank=True, null=True, verbose_name='Data da Ocorrência')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('documento_word', models.FileField(blank=True, null=True, upload_to='investigacao_outras_autoridades/word/', verbose_name='Documento Word')),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='investigacao_outras_autoridades/pdf/', verbose_name='Documento PDF')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cadastrado_em', models.DateField(auto_now_add=True, null=True, verbose_name='Cadastrado em')),
                ('cadastrado_por_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investigacoes_outras_autoridades_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Investigação de Outras Autoridades',
                'verbose_name_plural': 'Investigações de Outras Autoridades',
                'db_table': 'investigacao_outras_autoridades',
                'ordering': ['titulo'],
            },
        ),
    ]
