# Generated by Django 5.2 on 2026-03-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_apoio', '0003_investigacaooutrasautoridades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigacaooutrasautoridades',
            options={'ordering': ['-data_ocorrencia', 'titulo'], 'verbose_name': 'Investigação de Outras Autoridades', 'verbose_name_plural': 'Investigações de Outras Autoridades'},
        ),
        migrations.RemoveField(
            model_name='investigacaooutrasautoridades',
            name='documento_word',
        ),
        migrations.AddField(
            model_name='investigacaooutrasautoridades',
            name='fase_voo',
            field=models.CharField(blank=True, choices=[('LANCAMENTO', 'Lançamento'), ('ASCENSAO', 'Ascensão'), ('ORBITA', 'Órbita'), ('REENTRADA', 'Reentrada'), ('POUSO', 'Pouso'), ('PRE_LANCAMENTO', 'Pré-Lançamento'), ('OUTRO', 'Outro')], max_length=50, null=True, verbose_name='Fase do Voo'),
        ),
        migrations.AddField(
            model_name='investigacaooutrasautoridades',
            name='operador',
            field=models.CharField(blank=True, help_text='Ex: Orbital Sciences, SpaceX', max_length=200, null=True, verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='investigacaooutrasautoridades',
            name='veiculo',
            field=models.CharField(blank=True, help_text='Ex: Antares 130, Falcon 9, Ariane 5', max_length=200, null=True, verbose_name='Veículo'),
        ),
        migrations.AlterField(
            model_name='investigacaooutrasautoridades',
            name='autoridade_investigadora',
            field=models.CharField(help_text='Ex: FAA/AST, NTSB, ESA, Roscosmos', max_length=200, verbose_name='Autoridade Investigadora'),
        ),
        migrations.AlterField(
            model_name='investigacaooutrasautoridades',
            name='tipo_ocorrencia',
            field=models.CharField(choices=[('ACIDENTE', 'Acidente'), ('INCIDENTE_GRAVE', 'Incidente Grave'), ('INCIDENTE', 'Incidente'), ('ANOMALIA', 'Anomalia'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Ocorrência'),
        ),
    ]
