# Generated by Django 5.2 on 2026-03-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_apoio', '0004_alter_investigacaooutrasautoridades_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacaooutrasautoridades',
            name='tipo_ocorrencia',
            field=models.CharField(choices=[('ACIDENTE', 'Acidente'), ('INFORTÚNIO', 'Infortúnio'), ('INCIDENTE', 'Incidente'), ('ANOMALIA', 'Anomalia'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Ocorrência'),
        ),
    ]
