# Generated by Django 5.2 on 2026-03-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_apoio', '0005_alter_investigacaooutrasautoridades_tipo_ocorrencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoDiverso',
            fields=[
            ],
            options={
                'verbose_name': 'Documento Diverso',
                'verbose_name_plural': 'Documentos Diversos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('material_apoio.materialapoio',),
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
            ],
            options={
                'verbose_name': 'Formulário',
                'verbose_name_plural': 'Formulários',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('material_apoio.materialapoio',),
        ),
        migrations.CreateModel(
            name='NormaLegislacao',
            fields=[
            ],
            options={
                'verbose_name': 'Norma / Legislação',
                'verbose_name_plural': 'Normas e Legislações',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('material_apoio.materialapoio',),
        ),
        migrations.AlterField(
            model_name='materialapoio',
            name='categoria',
            field=models.CharField(choices=[('NORMA', 'Norma'), ('LEGISLACAO', 'Legislação'), ('MANUAL', 'Manual'), ('PROCEDIMENTO', 'Procedimento'), ('INSTRUCAO', 'Instrução'), ('REGULAMENTO', 'Regulamento'), ('FORMULARIO', 'Formulário'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Categoria'),
        ),
    ]
