# Generated by Django 5.2 on 2026-03-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_apoio', '0006_documentodiverso_formulario_normalegislacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialapoio',
            name='tipo_documento',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('COMUNICACAO', 'Comunicação'), ('IS', 'IS'), ('NPA', 'NPA'), ('FORMULARIO', 'Formulário'), ('MODELO', 'Modelo'), ('NORMAS_MANUAIS', 'Normas e Manuais'), ('ORIENTACAO', 'Orientação'), ('LEGISLACAO', 'Legislação'), ('POP', 'POP'), ('PROCESSO', 'Processo'), ('PROTOCOLO', 'Protocolo'), ('GLOSSARIO', 'Glossário'), ('REQUISICAO', 'Requisição'), ('TERMO', 'Termo'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Documento'),
        ),
    ]
